name: Publish Overrides
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-python@v5 
      with:
        python-version: '3.13'
    - run: |
        pip install requests
        python install_mods.py '${{ secrets.CURSEFORGE_KEY }}'
      
    - name: Commit in downloaded branch
      uses: EndBug/add-and-commit@v9
      with:
        add: '.'
        commit: '--message "update overrides"'
        # push: 'origin downloaded --set-upstream --force'
        new_branch: 'downloaded'
        default_author: 'github_actions'
