name: Publish Overrides
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0             # otherwise, you will fail to push refs to dest repo
    
    - uses: actions/setup-python@v5 
      with:
        python-version: '3.13'
    - run: |
        pip install requests
        python install_mods.py '${{ secrets.CURSEFORGE_KEY }}'

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        message: 'Update Overrides'
        branch: 'downloaded'
        github_token: ${{ secrets.GH_TOKEN }}
        force: true