name: Publish Overrides
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5 
      with:
        python-version: '3.13'
    - run: |
        pip install requests
        python install_mods.py '${{ secrets.CURSEFORGE_KEY }}'

    - name: Commit in downloaded branch
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        new_branch: downloaded
        
    - name: Create a Release
      uses: actions/create-release@v1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_branch: downloaded
        tag: ${{ github.run_number }}
        title: ${{ github.run_number }}
